export const surpriseMePrompts = [
  'A bicycle made of flowers with a basket of butterflies',
  'A giant snail reading a book under a mushroom umbrella',
  'A dragon made of ice cream breathing fire that is rainbow-colored',
  'A tree made of clouds with a person sitting on a swing made of rainbows',
  'A robot made of crystals holding a lantern made of lightning bugs',
  'A banana with a face and arms playing the guitar',
  "A cat made of sushi wearing a chef's hat and apron",
  'A tree with branches made of pencils and leaves made of books',
  'A snake made of spaghetti wearing a bowtie and holding a fork',
  'A unicorn made of neon lights galloping across the sky',
  'A mushroom house with a door made of a snail shell',
  'A flamingo wearing roller skates and holding a disco ball',
  'A tree made of jellybeans with a person climbing it',
  'A robot made of fire with a bucket of water and a hose',
  'A polar bear wearing a tutu and ice skating on a frozen pond',
  'A bicycle made of candy with a person riding it through a candyland',
  'A frog playing a saxophone on a lily pad in a pond',
  'A tree made of money with a person swimming in it',
  'A peacock made of feathers holding a paintbrush and canvas',
  "A seagull wearing a captain's hat and steering a hot air balloon",
  'A tree made of pizza with a person cutting a slice',
  'A dragon made of vines and flowers sleeping on a bed of moss',
  'A robot made of fruit and vegetables holding a fork and knife',
  'A snail made of clouds leaving a trail of rainbows',
  'A tree made of popcorn with a person eating it',
  'A chameleon made of candy blending in with its surroundings',
  'A giraffe made of balloons with a person holding its leash',
  'A tree made of ice with a person ice climbing',
  'A kangaroo wearing a tutu and ballet dancing on a stage',
  'A tree made of books with a person sitting on a branch reading',
  'A bear made of donuts with a person feeding it more donuts',
  'A robot made of water with a person surfing on it',
  'A tree made of feathers with a person lying on it like a pillow',
  'A butterfly made of gemstones flying over a mountain range',
  'A tree made of coral with a person scuba diving nearby',
  'A penguin wearing a top hat and holding a cane like a gentleman',
  'A tree made of snow with a person building a snowman',
  'A lobster made of sand walking on the beach',
  'A tree made of light bulbs with a person replacing one',
  'A hedgehog made of autumn leaves curled up in a pile of more leaves',
  'A tree made of crystals with a person meditating under it',
  'A seahorse made of seashells swimming in a tide pool',
  'A tree made of fireworks with a person watching them burst',
  'A caterpillar made of candy crawling through a field of flowers',
  'A tree made of Legos with a person building something on it',
  'A jellyfish made of watercolor paints floating in the ocean',
  'A tree made of gears with a person fixing one',
  'A koala made of cotton candy eating more cotton candy',
  'A tree made of mushrooms with a person picking one',
];
